blank_issues_enabled: false
contact_links:
  - name: Read the community guidelines
    about: "Please make sure you have read the submission guidelines before posting an issue"
    url: https://github.com/codyslexia/nexa/blob/master/CONTRIBUTING.md#-submitting-an-issue
  - name: Want to start a discussion?
    about: "Want to start a thread to discuss an idea? Use the discussions feature provided by GitHub."
    url: https://github.com/codyslexia/nexa/discussions
  - name: Have a question?
    url: https://codyslexia.com/nexa/discord
    about: "The Nexa Official Discord Server is a great place for questions to be asked and answered. Please use the #forum if you need help with your workspace!"
  - name: Are you looking for integration with a new tool?
    url: https://codyslexia.com/nexa/plugins
    about: "There are a lot of awesome Plugins for Nexa! Check here to see if there is a community plugin to integrate your tool."
