name: Lock Threads

on:
  schedule:
    # Once a day, at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    if: ${{ github.repository_owner == 'codyslexia' }}
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        id: lockthreads
        with:
          github-token: ${{ github.token }}
          # Lock issues after 30 days of being closed
          issue-inactive-days: '30'
          # Lock closed PRs after 5 days. This ensures that issues that stem from a PR are opened as issues, rather than comments on the recently merged PR.
          pr-inactive-days: '5'
          add-issue-labels: 'outdated'
          issue-comment: >
            This issue has been closed for more than 30 days. If this issue is still occuring, please open a new issue with more recent context.
          pr-comment: >
            This pull request has already been merged/closed. If you experience issues related to these changes, please open a new issue referencing this pull request.
